name: Continuous Integration
run-name: ${{ github.event.head_commit.message }}
on:
  push:
    branches:
      - main
jobs:
  check:
    name: Check Code
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.10"
      - name: Detect Project Version
        run: |
          ./gradlew currentVersion
      - name: Build with Gradle
        run: ./gradlew check
      - name: Publish ktor-app-server
        run: ./gradlew publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
